---
title: Mission Space Lab - Creators Guide
hero_image: images/banner.png
description: The mission space lab creator guide is designed to help teams to write programs that calculate the speed of the ISS. It introduces the task, program requirements, points towards other projects, and provide guidance on how and what to submit
version: 4
listed: false
copyedit: false
last_tested: '2023-08-08'
steps:
- title: "Introduction"
- title: "The Astro Pi computers"
  completion:
      - engaged
- title: "Writing your program and resources to help"
- title: "Optimising your program for the ISS"
- title: "Improving the accuracy of your program"
- title: "Testing your program"
- title: "Submitting your work"
  completion:
    - internal
- title: "Other Resources"
